### ISSUE TITLE
Is there a way to embed the Word Wise content into the mobi?

### ISSUE THREAD

**Issue by Wesley-Chan** [tmilovanov/wisecreator#14]
Hi. I was wondering if you know a way to generate such a EPUB for iOS devices.

Amazon hasn't implement Word Wise in their iOS Kindle app yet (maybe never). So I was thinking it'll be great if I can

1. Generate the Word Wise database with `wisecreator` 
1. Choose a Word Wise level
1. Somehow embed the Word Wise hints in the original .mobi file
1. Convert the .mobi to a .epub to read on iOS

**Comment by tmilovanov** [comment]
Hi!
No, I'm afraid it's not possible. As far as I know mobi doesn't have some speical features to support embedded word wise. All word wise information on kindle is stored outside of mobi in separate database.
