### ISSUE TITLE
Output format

### ISSUE THREAD

**Issue by ShaRocket** [tmilovanov/wisecreator#15]
Hello! 

After long hours of looking for this gem, long hours to try and run the program on Linux (only have a Mac available or work computer on which I couldn't run the .exe due to policy) when I finally managed to convert an ebook using the script, I shed a tear realising my reader doesn't support .mobi format. I'd contacted their tech support to see if there was any pending update or ANYTHING that could make it support .mobi (I'm very hopeful sometimes) but got a generic answer that .mobi format belongs to Amazon.
Now this is my last cry of help before I totally give up, I kinda know the answer already but just to be sure: it can only be in .mobi format, right ? My reader only support ePub (along with PDF, TXT, HTML, FB2 but don't think any of those would help either) format. Any way around this ?

Thanks in advance for your answer and super good job on that one !

**Comment by tmilovanov** [comment]
Hello!

"Word wise" is little connected with .mobi format itself, I think it's more about the reader which support or doesn't support the technology.
