### ISSUE TITLE
Sample books is not showing wordwise in kindle mobile app

### ISSUE THREAD

**Issue by kintul** [tmilovanov/wisecreator#17]
I have downloaded one of the sample books of yours and send it to kindle mobile app via  *@kindle.com email id, however i do not see word wise enabled for the books, can you please let me know if this only works for kindle device or kindle mobile app too...?

**Comment by tmilovanov** [comment]
Sample books aren't word wised by default. They exist to test that on your pc wisecreator works as it should. Follow the steps under "Kindle Android app" topic on the main page of the project to generate word wised books for kindle app
