### ISSUE TITLE
PermissionError: [WinError 31] A device attached to the system is not functioning

### ISSUE THREAD

**Issue by neljaouh** [tmilovanov/wisecreator#2]
Hi team,
I am trying to test wisecreator, but I keep getting the following error,
Do you have an ideas how to solve this ?

--

C:\Users\MyUserNamel\Documents\WordWise\wisecreator-master\executables>wisecreator.exe "Bernard Shaw - Pygmalion.mobi"
[.] Checking dependenices
[.] Converting mobi 2 mobi to generate ASIN
[.] Getting ASIN
[.] Getting rawml content of the book
[.] Collecting words
[.] Count of words: 26215
[.] Processing words:  |----------------------------------------| 1.2% Traceback
 (most recent call last):
  File "main.py", line 394, in <module>
  File "main.py", line 383, in main
  File "main.py", line 59, in print_progress
PermissionError: [WinError 31] A device attached to the system is not functioning
[3252] Failed to execute script main
Exception ignored in: <_io.TextIOWrapper name='<stdout>' mode='w' encoding='utf-8'>
PermissionError: [WinError 31] A device attached to the system is not functioning

**Comment by tmilovanov** [comment]
@neljaouh Thank you for posting the issue.

Resolved, executables have been updated.
