### ISSUE TITLE
Support for macos

### ISSUE THREAD

**Issue by hungdev** [tmilovanov/wisecreator#20]
Thank for your code <3

**Comment by eaglez1111** [comment]
so does this code work on MacOS? I installed Calibre but I am still getting this error when i try to run wisecreater:
`-bash: ebook-convert: command not found
`

**Comment by rafalschmidt97** [comment]
Any news?

**Comment by xxyzz** [comment]
The python script should works on mac. To fix that command not found error you should add calibre commands to your PATH or simply install calibre via homebrew. You can also try this calibre plugin: https://github.com/xxyzz/WordDumb
