### ISSUE TITLE
Exe for Windows not code signed?

### ISSUE THREAD

**Issue by eugeniafranzoni** [tmilovanov/wisecreator#24]
Hi! the EXE file https://github.com/tmilovanov/wisecreator/blob/master/executables/wisecreator.exe seems not "code signed", so it's impossible to execute it under Windows 10. It seems the same problem which is described here: https://stackoverflow.com/questions/44377666/pyinstaller-exe-throws-windows-defender-no-publisher, so maybe it's enough to follow this link: https://stackoverflow.com/questions/252226/signing-a-windows-exe-file

**Comment by tmilovanov** [comment]
@eugeniafranzoni Hi!

Yes, executables are not code signed. Though it doesn't prevent them to be run. Windows 10 gives you a warning but you can skip it. See these screenshots:

![1](https://user-images.githubusercontent.com/5417938/63411503-582d8b00-c3fe-11e9-8322-e366ebfa4e71.png)

![2](https://user-images.githubusercontent.com/5417938/63411501-582d8b00-c3fe-11e9-9172-57e72fe0057a.png)
