### ISSUE TITLE
All words have difficulty level 1 assigned

### ISSUE THREAD

**Issue by TheScriptingVajra** [tmilovanov/wisecreator#28]
Even though senses.csv has a different difficulty level for all words, it is not used and all words have level 1 assigned.

**Comment by zpcc** [comment]
You can use the exe [here](https://ci.appveyor.com/api/buildjobs/eq1x7qck67akta6c/artifacts/dist.zip) or run the script to try again, it works on my win10. 

If it still fails, you can upload your book and the output folder here. Or just the output folder of the test books provided in git. Besides, you can use [sqlitebrowser](https://sqlitebrowser.org/) to open your .kll file to debug.

**Comment by TheScriptingVajra** [comment]
> You can use the exe [here](https://ci.appveyor.com/api/buildjobs/eq1x7qck67akta6c/artifacts/dist.zip) or run the script to try again, it works on my win10.
> 
> If it still fails, you can upload your book and the output folder here. Or just the output folder of the test books provided in git. Besides, you can use [sqlitebrowser](https://sqlitebrowser.org/) to open your .kll file to debug.

Thanks a lot. This is working.

**Comment by gallexy** [comment]
I just wonder if it is possible to do it with this tool.
