### ISSUE TITLE
UnicodeDecodeError

### ISSUE THREAD

**Issue by superxuxin** [tmilovanov/wisecreator#33]
[.] Checking dependenices
[.] Converting mobi 2 mobi to generate ASIN
[.] Getting ASIN
[.] Getting rawml content of the book
[.] Collecting words
[.] Count of words: 45156
Traceback (most recent call last):
  File "main.py", line 395, in <module>
  File "main.py", line 359, in main
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 6710: illegal
 multibyte sequence
[1540] Failed to execute script main

Could you have a fixed exe file please?

**Comment by tmilovanov** [comment]
Fixed in v1.1
