### ISSUE TITLE
How to generate senses.csv

### ISSUE THREAD

**Issue by avsej** [tmilovanov/wisecreator#4]
Hi, this i not really the issue, but rather question.

How did you generate `senses.csv` file?

**Comment by avsej** [comment]
Nevermind, I see that it is just kindle's dictionary converted to CSV

**Comment by szeseong** [comment]
Hi,

How do you match sense_id to the word?

**Comment by avsej** [comment]
The database lives at `/system/kll/kll.en.en.klld`, you can open open it with `sqlitebrowser` and see the words in `lemmas` table.

**Comment by ntan234** [comment]
> The database lives at `/system/kll/kll.en.en.klld`, you can open open it with `sqlitebrowser` and see the words in `lemmas` table.
I want to change the dictionary, can I?
I see he use metadata of Dictionary in main.py, but don't know how to change it to another dictionary
