### ISSUE TITLE
Error: Resource averaged_perceptron_tagger not found

### ISSUE THREAD

**Issue by amitguptagwl** [tmilovanov/wisecreator#40]
I'm facing following error when I'm running the utility through the source code;

```
  File "~/.local/lib/python3.8/site-packages/nltk/data.py", line 585, in find
    raise LookupError(resource_not_found)
LookupError: 
**********************************************************************
  Resource averaged_perceptron_tagger not found.
  Please use the NLTK Downloader to obtain the resource:

  >>> import nltk
  >>> nltk.download('averaged_perceptron_tagger')
  
  For more information see: https://www.nltk.org/data.html

  Attempted to load taggers/averaged_perceptron_tagger/averaged_perceptron_tagger.pickle

```

Though It is generating the Language layer file (ie .kll) But getting no word wise hint when opening the ebook on Kindle.

**Comment by tmilovanov** [comment]
Did you follow instruction? You should run `python3 -m pip install .` right after you clone repository. NLTK has it's own data that it needs to download. Or you can run python3 interactive console and write those lines:


`import nltk`
`nltk.download('averaged_perceptron_tagger')`

**Comment by amitguptagwl** [comment]
My bad i missed the suggested step. It is working fine. I have tried with two books
