### ISSUE TITLE
How can I bypass this thing.

### ISSUE THREAD

**Issue by Roybabu** [tmilovanov/wisecreator#44]
mint@mint:~/Calibre Library/Leigh Bardugo/Ruin and Rising_ Book 3 (14)$ ./wisecreator rr.mobi
[.] Checking dependencies
[.] Getting ASIN
[.] Getting rawml content of the book
Traceback (most recent call last):
  File "wisecreator/main.py", line 334, in <module>
  File "wisecreator/main.py", line 330, in main
  File "wisecreator/main.py", line 314, in process
  File "wisecreator/main.py", line 288, in wordwise
  File "wisecreator/book.py", line 25, in get_glosses
  File "wisecreator/book.py", line 97, in _get_rawml_content
FileNotFoundError: [Errno 2] No such file or directory: 'rr-WordWised/unpacked/mobi7/rr.rawml'
[4722] Failed to execute script main

**Comment by Roybabu** [comment]
@tmilovanov

**Comment by ali-oem** [comment]
> mint@mint:~/Calibre Library/Leigh Bardugo/Ruin and Rising_ Book 3 (14)$ ./wisecreator rr.mobi
> [.] Checking dependencies
> [.] Getting ASIN
> [.] Getting rawml content of the book
> Traceback (most recent call last):
> File "wisecreator/main.py", line 334, in
> File "wisecreator/main.py", line 330, in main
> File "wisecreator/main.py", line 314, in process
> File "wisecreator/main.py", line 288, in wordwise
> File "wisecreator/book.py", line 25, in get_glosses
> File "wisecreator/book.py", line 97, in _get_rawml_content
> FileNotFoundError: [Errno 2] No such file or directory: 'rr-WordWised/unpacked/mobi7/rr.rawml'
> [4722] Failed to execute script main

Your .mobi is in English Language?(Check metadata)

**Comment by tmilovanov** [comment]
@Roybabu 
Hi! Thank you for submitting the issue.
Can you please send me your book on email: timcess@gmail.com? I will debug this

**Comment by Roybabu** [comment]
> > mint@mint:~/Calibre Library/Leigh Bardugo/Ruin and Rising_ Book 3 (14)$ ./wisecreator rr.mobi
> > [.] Checking dependencies
> > [.] Getting ASIN
> > [.] Getting rawml content of the book
> > Traceback (most recent call last):
> > File "wisecreator/main.py", line 334, in
> > File "wisecreator/main.py", line 330, in main
> > File "wisecreator/main.py", line 314, in process
> > File "wisecreator/main.py", line 288, in wordwise
> > File "wisecreator/book.py", line 25, in get_glosses
> > File "wisecreator/book.py", line 97, in _get_rawml_content
> > FileNotFoundError: [Errno 2] No such file or directory: 'rr-WordWised/unpacked/mobi7/rr.rawml'
> > [4722] Failed to execute script main
> 
> Your .mobi is in English Language?(Check metadata)

Yes it is in English.

**Comment by Roybabu** [comment]
> @Roybabu
> Hi! Thank you for submitting the issue.
> Can you please send me your book on email: [timcess@gmail.com](mailto:timcess@gmail.com)? I will debug this

Check your mailbox please.

**Comment by Roybabu** [comment]
@tmilovanov  any update on this.
