### ISSUE TITLE
README document improvement suggestion

### ISSUE THREAD

**Issue by YingcaiDong** [tmilovanov/wisecreator#46]
I suggest adding `pip install wheel` in the script section.

Below are the details:

I followed the 'Script' instruction on my Mac. And the command `python3 -m pip install .` always complained of an error with a message that said: invalid command 'bdist_wheel.' 

After some search, this error was caused by not installing 'wheel.' I installed the wheel using `pip install wheel`, and everything works like a charm.

**Comment by tmilovanov** [comment]
Added
