### ISSUE TITLE
Got error message "ModuleNotFoundError: No module named 'cursor'"

### ISSUE THREAD

**Issue by bachmx** [tmilovanov/wisecreator#8]
I tried to run in MacOs and terminal tell me that:

File "/Users/bachmx/Downloads/wisecreator/main.py", line 13, in <module>
    import cursor
ModuleNotFoundError: No module named 'cursor'

How can i fix it?

**Comment by tmilovanov** [comment]
Try to install python module named 'cursor': python -m pip install cursor

**Comment by bachmx** [comment]
Thank you! It's working!
